### ISSUE TITLE
Today's Hours in footer are not dynamic

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#104]
How do you manage "Today's Hours" on the current website?

**Comment by theBrarian** [comment]
We have a Sharepoint list with days of the week and the hours that populates the footer. We can go in and manually change them if there is an unexpected change in the posted times.

**Comment by gbohara** [comment]
currently it is spread across various tpl files (10 different tpl files). We at least need to store this value in a variable and then read from there in all these pages.

**Comment by gbohara** [comment]
It has been made dynamic and moved to block instead of 10 different tpl files. This should also fix the hours for Saturday and  Sunday.

To be consistent with the hours on the right side of the site (see. http://nihlibrary.prod.acquia-sites.com/services/requests/bioinformatics-resources-registration), the format has been changed to "7:45 AM to 8:00 PM EST"  from "7:45AM-8PM". 

If needed, the format can be changed.

**Comment by alwaysmashana** [comment]
Issue solved. Closing ticket.
