### ISSUE TITLE
Agency Homepage: Ordering doesn't work on Features

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#109]
This is clearly a bug. The change appears in the editing view, but not on the site once saved.

**Comment by tgifford-webfirst** [comment]
See https://www.drupal.org/node/1444798 and https://www.drupal.org/node/2075593.

**Comment by tgifford-webfirst** [comment]
Fixed with a workaround in http://nihlibrary.prod.acquia-sites.com/admin/structure/views/view/list_features_home/edit/default.

**Comment by mashanadavis** [comment]
Is there a reason a workaround had to be used? Is there an issue with the module/feature being used? How does this impact our use of this feature going forward?

**Comment by tgifford-webfirst** [comment]
Whenever we use a view based on the "Field collection item" entities, the ordering of the items shown in the view is not automatically correlated to the order they are shown on the parent node edit form. The workaround is to use relationships to join to the parent node, then back to a second copy of the field collection item, and then add additional filters to correlate the redundant field collection items. 

We could also replace the field_collection_views module, but that would take additional time. That being said, it is not a priority because the workaround works, and we would implement any similar "features" on the site with a different technique if they come up in the future.

**Comment by mashanadavis** [comment]
Sounds good. Just trying to understand the workarounds.

**Comment by alwaysmashana** [comment]
Reordering works. Closing ticket.
