### ISSUE TITLE
Search Results: Debug and fix  "_empty_" on blank search

### ISSUE THREAD

**Issue by gbohara** [NIHL/Drupal7-Migration#125]
http://nihlibrarystg.prod.acquia-sites.com/search/site

The glossary section contains item with "_empty_". This needs to be removed?

**Comment by mashanadavis** [comment]
If the results do not contain items starting with a particular letter then the letter should be grayed out or not clickable. The word "empty" should not appear in the A-Z list.

**Comment by tgifford-webfirst** [comment]
It appears the original developer was in the process of debugging the glossary, because there are two glossary-related modules enabled: http://nihlibrary.dev.dd:8083/admin/modules (search glossary), one of which is custom and clearly unfinished, and has German text in it. I'm disabling the custom module for a start.

**Comment by tgifford-webfirst** [comment]
This appears to be caused by a missing title for one resource, and non-English characters in other cases: http://nihlibrary.prod.acquia-sites.com/search/site?f[0]=ss_apachesolr_glossary%3A

The "_empty_" facet is an artifact of how PHP deserializes the JSON response from Solr, so you actually have to search with the _empty_ text removed from the URL, as I have above.

The upshot is that we need to transliterate international characters for the glossary module, which may be possible to do in a hook in our own custom module instead of patching the contrib module.

I deleted the resource without a title, but it may be worth looking at the ERM import scripts to catch that in the future.

**Comment by jronmorgan** [comment]
I will make sure to check for those in the future. I believe there were only one or two and rather than reimport I had intended to just clean them up after. Maybe a mistake.

-john

________________________________

**Comment by tgifford-webfirst** [comment]
I pushed an issue branch to prod to fix the Solr index. I'll back that out now and merge the code into master when you are done with the multi-index stuff.
