### ISSUE TITLE
iTrust/EZproxy issue with Remote Access

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#132]
When logging in through remote access, the following message appeared:

"The requested page "/ezpsignin/NIHhttp://nihlibrary.nih.gov" could not be found."

Ted seems to think that the functionality is working but there may be some issue with iTrust or EZproxy. 

Can you review this, please? 

I'm guessing that this is a priority given that we're planning to test authentication. So, I'm assigning it to BR1.

**Comment by jronmorgan** [comment]
Can you tell me, what is the exact navigation you used to get to this point, please?

-john

________________________________

**Comment by mashanadavis** [comment]
My workflow:

  1.  Started here: http://nihlibrarystg.prod.acquia-sites.com/agency/nih
  2.  Clicked Login and select NIH Remote Access
  3.  Logged in using my NIH credentials
  4.  redirected to http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/ezpsignin/NIHhttp://nihlibrary.nih.gov<http://nihlibrarystg.prod.acquia-sites.com.ezproxy.nihlibrary.nih.gov/ezpsignin/NIHhttp:/nihlibrary.nih.gov>
which gave the error message.

**Comment by bridgetburns** [comment]
Same for me.

**Comment by jronmorgan** [comment]
When you say "Logged in using my NIH credentials" does that mean right side "Insert your PIV card into smart card reader" or left side entry of User Name and Password?
(I don't have anything that works for either BTW)

-john

________________________________

**Comment by mashanadavis** [comment]
I used my smartcard. Not sure about Bridget.

**Comment by bridgetburns** [comment]
User name and password for me.

**Comment by jronmorgan** [comment]
ok.. I will try and step through it although I don't have a working user and pass. I tried the "drupal" user that Ben had set up but its not working here. I'll see what I can find.

-john

________________________________

**Comment by mashanadavis** [comment]
Do you need credentials?

**Comment by tgifford-webfirst** [comment]
The drupal user works for me, but only from the "Temporary" user account login pages, not the iTrust page, and only on the nihlibrarystg domain, not prod.

**Comment by jronmorgan** [comment]
I think I see something suspicious in the url being sent to itrust.. let me look at this a little more.. But yes, some credentials would be useful..

-john

________________________________

**Comment by mashanadavis** [comment]
What credentials do you need? I can provide my library provided account.

**Comment by mashanadavis** [comment]
From the status meeting on April 27:

John is investigating this issue: iTrust is appending the nihlibrary.nih.gov to the Acquia URL. Ted seems to think that EZproxy may need the current PROD URL to be added the configuration.

**Comment by jronmorgan** [comment]
This is making debugging difficult.

The short of it is that I think we likely have an EZProxy misconfiguration.

Anyway, background for the issue is currently as follows:

Beginning the process at: http://nihlibrarystg.prod.acquia-sites.com/agency/nih


Main Menu Login link is as: NIH Remote Access = (local function) sso-redirect/NIH


sso-redirect/NIH redirects to:

    https://itrusteauth.nih.gov/NIHLibraryExt/link.asp?url=http://nihlibrarystg.prod.acquia-sites.com/ezpsignin/NIH


The above URL seems perfectly valid.


itrusteauth.nih.gov then presents the following page:

https://itrusteauth.nih.gov/CertAuthV2/forms/NIHPivOrFormLogin.aspx?TYPE=33554433&REALMOID=06-8a9f668a-27c3-47fd-87f3-b9e0c55e4555&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-itrusteauth%2enih%2egov&TARGET=-SM-HTTPS%3a%2f%2fitrusteauth%2enih%2egov%2fNIHLibraryExt%2flink%2easp%3furl%3dhttp%3a%2f%2fnihlibrarystg%2eprod%2eacquia--sites%2ecom%2fezpsignin%2fNIH


unescaped , the above URL reads as:

https://itrusteauth.nih.gov/CertAuthV2/forms/NIHPivOrFormLogin.aspx?TYPE=33554433&REALMOID=06-8a9f668a-27c3-47fd-87f3-b9e0c55e4555&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-itrusteauth.nih.gov&TARGET=-SM-HTTPS://itrusteauth.nih.gov/NIHLibraryExt/link.asp?url=http://nihlibrarystg.prod.acquia--sites.com/ezpsignin/NIH


Potential issues with the above:

- there are now 2 dashes in the host name. This could be nothing, could be everything.


apparently, a successful login then attempts to redirect to the following url:

/ezpsignin/NIHhttp://nihlibrary.nih.gov

which is completely broken.
- host is *after* the form data
- http instead of https
- this is staging, the correct host url should be: http://nihlibrarystg.prod.acquia-sites.com

Testing a little further. The corrected URL works perfectly fine:
    http://nihlibrarystg.prod.acquia-sites.com/ezpsignin/NIH



________________________________

**Comment by cmndr-king** [comment]
Additional info on EZProxy posted to Basecamp.


-James
_______________________________
James King, MLS, FSLA
(301) 496-2187

http://about.me/cmndr_king

**Comment by tgifford-webfirst** [comment]
The last URL in John's comment should have the ezproxy domain: http://nihlibrarystg.prod.acquia-sites.com.ezproxyhhs.nihlibrary.nih.gov/ezpsignin/NIH

**Comment by mashanadavis** [comment]
New tickets were created related to authentication #151 and #152. They are in progress.
