### ISSUE TITLE
Agency Homepage: Cannot assign Quick Links to appropriate agency

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#15]
Homepage, Section 2, Box 1 - For an agency homepage, not NIH or Public, how do I display proper menu? I created a menu called "IHS Quick Links" to use for Agency Homepage = IHS. How do I connect these two?

**Comment by mashanadavis** [comment]
Quick Links (on the homepage, Section 2, Box 1, are controlled by a menu). NIH and Public are displaying, but other customer groups (e.g. IHS) will use different quick links. I created a menu (http://nihlibrarystg.prod.acquia-sites.com/admin/content), but cannot figure out how to make the menu appear on the homepage for this customer group. The customer group's agency homepage is http://nihlibrarystg.prod.acquia-sites.com/node/521.

**Comment by tgifford-webfirst** [comment]
The system is using the Context module to add the menu block for the Quick Links menu to all agency homepages (as well as the default home page). We recommend changing this approach as follows:

* Remove the Agency Homepage content type condition for the existing home_site context
* Add a multi-value Quick Links link field to the Agency Homepage content type
* Create a view with a block to display the quick links for a specified Agency Homepage
* Add a new context (home_agency) with an Agency Homepage content type condition that displays the new view with the other blocks (Latest News and Latest Training).
* Override/extend the Omega hook_preprocess_block() implementation to make sure the block--nav.tpl.php template is used for the quick links view instead of the default block.tpl.php (keeping the same <nav> semantic markup).

This means *not* using the standard Drupal menus for these quick links. Do you have any objections to this approach?

**Comment by mashanadavis** [comment]
Sounds good. Before agreeing to this, how easy will it be to add, edit, remove, etc. quick links for a particular agency? Our staff will be the ones using this feature, so ease-of-use of important.

**Comment by tgifford-webfirst** [comment]
It's as easy as clicking the Edit link at the top of the Agency Homepage. We will proceed.

**Comment by tgifford-webfirst** [comment]
This is published on dev. Please review and edit the IHS Agency Homepage, and let me know if this is ready to publish.

**Comment by tgifford-webfirst** [comment]
The Quick Links are hidden on Agency Homepages without any, as you would expect.

**Comment by mashanadavis** [comment]
Nice! This is much simpler than the previous set up. Our content authors will be pleased. I say let's go with this and push to STG.

**Comment by tgifford-webfirst** [comment]
Pushed to STG. Please close when verified.
