### ISSUE TITLE
Journal Title error message

### ISSUE THREAD

**Issue by bridgetburns** [NIHL/Drupal7-Migration#154]
All Online Journals / A
When you click any title in the first page of results, you get this error:  

Page not found
The requested page "/node/XXXX" could not be found.

Other A titles yield the same errors. Other titles are unaffected. Short of clicking every title, not sure how to troubleshoot this.

**Comment by tgifford-webfirst** [comment]
This is because the Solr index was overwritten by another environment with old content in it. The node ids for those Journals are different in the current production MySql database. This may have happened when the multi-core issues were being worked on--John, is that possible?

I will wipe and re-create the index. While that is happening, searches will return partial or no results.

**Comment by jronmorgan** [comment]
I have not played with those in a while so I doubt it was me... But who knows..  That does remind me however that I need to proceed with the final subscription and getting multiple cores set up. I will do that now.

-john

________________________________

**Comment by tgifford-webfirst** [comment]
The indexing is running in a screen session via drush, and should complete within three hours.

**Comment by bridgetburns** [comment]
That resolved the issue. Thanks.
