### ISSUE TITLE
Login - test HHS locations for PIV and/or NIH u/p credentials

### ISSUE THREAD

**Issue by bridgetburns** [NIHL/Drupal7-Migration#160]

**Comment by alwaysmashana** [comment]
During testing with an APSR user, after authentication they were directed to the IOS homepage (http://nihlibrary.prod.acquia-sites.com/agency/os) instead of the ASPR homepage (http://nihlibrary.prod.acquia-sites.com/agency/os/aspr).

Users should be directed to the correct agency homepage once authenticated.

**Comment by gbohara** [comment]
Was it for Library-Provided account or Agency PIV Card / Credentials?

**Comment by alwaysmashana** [comment]
Testing was for PIV and u/p. Some people tested their LPAs as well.
