### ISSUE TITLE
WYSIWYG needs to be installed

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#30]

**Comment by jronmorgan** [comment]
Where do you want to see wysiwyg in place? Can you provide a link to an editing page that would use it? I installed the wysiwyg module but am not sure where it should be used.

**Comment by mashanadavis** [comment]
The WYSIWYG should be turned on for all content types. Right now, content editors can only put in limited HTML <tags>.

**Comment by mashanadavis** [comment]
Hi Ted - I see this was moved and assigned to you. We want to control formatting of content as much as possible. Can you advise on whether we should use the WYSIWYG or not to do this?

**Comment by tgifford-webfirst** [comment]
You can use a WYSIWYG editor to create controlled markup just as well as plain text. WYSIWYG is just a more convenient way for editors to generate the raw markup that is then fed into Drupal's text formats, which control the allowed elements (among other things).

If you are going down the path of controlling markup, which is a best practice, the corresponding design elements and CSS styles should be documented and developed at the same time. This relates to building the theme in #49. We can enable the WYSIWYG for now, but we will likely need to re-configure the WYSIWYG to support the full range of design elements in the new theme.

**Comment by tgifford-webfirst** [comment]
I configured the text formats to filter allowed tags. All existing tags should be included, so I don't expect that setting to break anything.

However, I disabled the "Convert line breaks into HTML (i.e. <br> and <p>)" filter, since it is not compatible with WYSIWYG. I will analyze the content Monday to locate places that will break, and add manual <br> and <p> tags as appropriate.

**Comment by mashanadavis** [comment]
Thanks. We discussed the potential of using a "white list" to strip out unwanted HTML tags when/if the WYSIWYG and CSS are officially implemented. This would probably be best to discussion when planning the new theme.

**Comment by mashanadavis** [comment]
Updating again...

Can we turn on the WYSIWYG for now just for the content migration team? Also, the WYSIWYG should have a file lookup feature.

**Comment by tgifford-webfirst** [comment]
You may have noticed that WYSIWYG has been enabled. I'm almost ready to move this to review, pending the "convert line breaks to html" analysis.

**Comment by tgifford-webfirst** [comment]
I converted all the old content to work with WYSIWYG so that paragraphs would not get merged together when you next edited the content. I also changed the content to use the "Filtered HTML" format instead of "Extended HTML", where possible. There are still a few trainings/sessions that need review, but for the most part this is ready to go from our end.

If you need additional HTML elements to be available, please open a new ticket.
