### ISSUE TITLE
Instruction: Training Category not functioning properly on List View

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#52]
Removed the Training Category from the Training Session content type, left it in the Training content type. Since moving it, the facet doesn't work properly---select an option from multi-select but option doesn't stick.

http://nihlibrarystg.prod.acquia-sites.com/node/166

This page is controlled by a View: http://nihlibrarystg.prod.acquia-sites.com/admin/structure/views/view/latest_training/edit/page_1

**Comment by tgifford-webfirst** [comment]
1. It appears the training category field is in both content types. The calendar view is working because it queries the category field values attached to the Training Session.

   If you want to use the category on the (parent) Training, we will need to populate the category field for each Training, then update the views.

2. The List View has been fixed to work the way the Calendar view works.
