### ISSUE TITLE
Does the ERM import add new NIH Subject terms?

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#67]
When importing new ERM data, if a term is in the import file will it be added if not already in the NIH Subject taxonomy?

**Comment by cmndr-king** [comment]
I don't think so.  The current files I just loaded still align to the old subjects so we're going to have to massage the data before loading.  The intention is that everything loaded connects to the NIH Subject taxonomy and will not introduce anything new.  If we do run into something new, will an error be generated so that we can flag it and fix it?
