### ISSUE TITLE
Instruction: Can you email waitlisted registrants?

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#84]
There needs to be an easy way to send email to both the registrants and the waitlist folks for the instructors.

**Comment by tgifford-webfirst** [comment]
The registration and registration_waitlist modules do not support emailing waitlisted registrants. The email only goes to "active" registrants, such as those in the "Complete" registration state. If we convert the "Wait List" state to "active", it will defeat the purpose, because all "active" registrations count against the registration limit, which is not what we want from our waitlist.

That being said, this could be accomplished with custom code. All of the existing registration email-sending code could even be reused if we do a little trickery with a static cache, so it might be worth the effort. Would you like an estimate?

**Comment by mashanadavis** [comment]
Thanks for the explanation. Yes, please provide an estimate.

**Comment by mashanadavis** [comment]
Is there a way to manually identify the waitlist registrants? We can export (manually perhaps) the addresses and send an email.

**Comment by tgifford-webfirst** [comment]
The registration module lists all registrations, including waitlisted ones, on the "Manage registrations" page in a table. There is no export option, but that appears to have been added with the views_data_export module, at the "Assistants" task underneath the "Manage registrations" tab (find the orange CSV link near the bottom). We could update that view to include the registration status.

The same view also has another display at path /registrations, which lists all the registrations. You probably want that to filtered somehow, but nevertheless it can be used to export all registrations from all trainings as well.

Both of those exports appear to be limited to only 10 items due to a configuration setting, and you probably want them to be unlimited.

**Comment by mashanadavis** [comment]
This sounds like a feasible solution. How long will it take to implement?

**Comment by cmndr-king** [comment]
Ted - please also watch for a larger "tipping point" with this module.  The previous firm adopted this module to quickly provide a way to manage classes but as we learn more about it, we're seeing that the module is incomplete.  I'm fine with contributing improvements to modules back to the community but if it would be faster and cheaper to move to another solution, I'm open to that too.

**Comment by tgifford-webfirst** [comment]
The registration State has been added in the places mentioned above. See:

* http://nihlibrarystg.prod.acquia-sites.com/node/1411/registrations/assistants
* http://nihlibrarystg.prod.acquia-sites.com/registrations
* The CSV downloads for each of the above links.
